version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: ./app
    container_name: my_flask
    command: gunicorn --bind 0.0.0.0:5000 main:app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/my_db
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5555
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - pgadmin
volumes:
  pgdata: {}